In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [9]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36'
}

webpage = requests.get(
    'https://www.ambitionbox.com/list-of-companies?page=1',
    headers=headers
).text

In [25]:
Soup = BeautifulSoup(webpage , 'lxml')

In [26]:
Company = Soup.find_all('div' , class_='companyCardWrapper__primaryInformation')

In [27]:
len(Company)

20

In [63]:
Name = []
Rating = []
Reviews = []
Ctype = []
Hq = []
HR = []
CR = []
for i in Company:
    Name.append(i.find('h2').text.strip())
    Rating.append(i.find('div',class_='rating_text rating_text--md').text.strip())
    Reviews.append(i.find('span',class_='companyCardWrapper__companyRatingCount').text.strip())
    info = i.find('span', class_='companyCardWrapper__interLinking').text.strip().split('|')
    Ctype.append(info[0].strip())
    Hq.append(info[1].strip())
    ratings = i.find_all('span', class_='companyCardWrapper__ratingValues')
    HR.append(ratings[0].text.strip() if len(ratings) > 0 else None)
    CR.append(ratings[1].text.strip() if len(ratings) > 1 else None)

D = {'Name':Name,'Rating':Rating,'Reviews':Reviews,'Company_Type':Ctype,'Headquaters':Hq,'Highly Rated':HR,'Critically Rated':CR}
df = pd.DataFrame(D)
df

,Name,Rating,Reviews,Company_Type,Headquaters,Highly Rated,Critically Rated
0,TCS,3.3,(1.2L),IT Services & Consulting,Bengaluru +448 other locations,Job Security,"Promotions, Salary, Work Satisfaction"
1,Accenture,3.7,(75.2k),IT Services & Consulting,Bengaluru +261 other locations,"Promotions, Salary, Work Satisfaction",None
2,Wipro,3.6,(66.4k),IT Services & Consulting,Hyderabad +375 other locations,"Promotions, Salary, Work Satisfaction",None
3,Cognizant,3.7,(62.7k),IT Services & Consulting,Hyderabad +233 other locations,"Promotions, Salary, Work Satisfaction",None
4,Capgemini,3.6,(54.8k),IT Services & Consulting,Bengaluru +188 other locations,"Work Life Balance, Job Security","Promotions, Salary, Work Satisfaction"
5,HDFC Bank,3.8,(53.9k),Banking,Mumbai +1865 other locations,"Job Security, Skill Development","Promotions, Salary"
6,Infosys,3.5,(49.9k),IT Services & Consulting,Bengaluru +247 other locations,Job Security,"Promotions, Salary, Work Satisfaction"
7,HCLTech,3.4,(47k),IT Services & Consulting,Chennai +232 other locations,"Promotions, Salary, Work Satisfaction",None
8,ICICI Bank,4.0,(46.7k),Banking,Mumbai +1449 other locations,"Job Security, Promotions, Skill Development",None
9,Tech Mahindra,3.3,(44.2k),IT Services & Consulting,Hyderabad +323 other locations,"Promotions, Salary, Work Satisfaction",None
10,Genpact,3.6,(43.4k),Analytics & KPO,Hyderabad +181 other locations,Job Security,"Promotions, Salary, Work Satisfaction"
11,TP,3.9,(39.7k),BPO,Mumbai +259 other locations,"Work Life Balance, Job Security, Skill Develop...",None
12,Axis Bank,3.6,(34.1k),Banking,Mumbai +1535 other locations,"Promotions, Work Satisfaction, Company Culture",None
13,Jio,4.4,(34.1k),Telecom,Mumbai +1966 other locations,"Job Security, Skill Development, Company Culture",None
14,Concentrix Corporation,3.5,(32.9k),BPO,Bengaluru +185 other locations,Job Security,"Promotions, Salary, Work Satisfaction"
15,Amazon,3.9,(32.4k),Internet,Bengaluru +521 other locations,"Company Culture, Work Life Balance, Salary",Promotions
16,Reliance Retail,3.9,(27.8k),Retail,Mumbai +1167 other locations,"Job Security, Skill Development, Work Life Bal...",Promotions
17,iEnergizer,4.6,(27.5k),BPO,Noida +55 other locations,"Company Culture, Work Life Balance, Work Satis...",None
18,LTM Limited,3.6,(27k),IT Services & Consulting,Bengaluru +146 other locations,"Promotions, Salary, Work Satisfaction",None
19,HDB Financial Services,3.9,(26.3k),NBFC,Mumbai +1099 other locations,"Promotions, Salary",None

In [69]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

Final = pd.DataFrame()

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36'
}

for j in range(1, 11):

    url = f'https://www.ambitionbox.com/list-of-companies?page={j}'

    webpage = requests.get(url, headers=headers).text

    Soup = BeautifulSoup(webpage, 'lxml')

    Company = Soup.find_all('div', class_='companyCardWrapper__primaryInformation')

    Name = []
    Rating = []
    Reviews = []
    Ctype = []
    Hq = []
    HR = []
    CR = []

    for i in Company:

        Name.append(i.find('h2').text.strip())

        Rating.append(i.find('div', class_='rating_text rating_text--md').text.strip())

        Reviews.append(i.find('span', class_='companyCardWrapper__companyRatingCount').text.strip())

        info = i.find('span', class_='companyCardWrapper__interLinking').text.strip().split('|')

        Ctype.append(info[0].strip())

        Hq.append(info[1].strip() if len(info) > 1 else None)

        ratings = i.find_all('span', class_='companyCardWrapper__ratingValues')

        HR.append(ratings[0].text.strip() if len(ratings) > 0 else None)

        CR.append(ratings[1].text.strip() if len(ratings) > 1 else None)

    df = pd.DataFrame({
        'Name': Name,
        'Rating': Rating,
        'Reviews': Reviews,
        'Company Type': Ctype,
        'Headquarters': Hq,
        'Highly Rated For': HR,
        'Critically Rated For': CR
    })

    Final = pd.concat([Final, df], ignore_index=True)

print(Final.shape)
Final.head(50)

(200, 7)

,Name,Rating,Reviews,Company Type,Headquarters,Highly Rated For,Critically Rated For
0,TCS,3.3,(1.2L),IT Services & Consulting,Bengaluru +448 other locations,Job Security,"Promotions, Salary, Work Satisfaction"
1,Accenture,3.7,(75.2k),IT Services & Consulting,Bengaluru +261 other locations,"Promotions, Salary, Work Satisfaction",None
2,Wipro,3.6,(66.4k),IT Services & Consulting,Hyderabad +375 other locations,"Promotions, Salary, Work Satisfaction",None
3,Cognizant,3.7,(62.7k),IT Services & Consulting,Hyderabad +233 other locations,"Promotions, Salary, Work Satisfaction",None
4,Capgemini,3.6,(54.8k),IT Services & Consulting,Bengaluru +188 other locations,"Work Life Balance, Job Security","Promotions, Salary, Work Satisfaction"
5,HDFC Bank,3.8,(53.9k),Banking,Mumbai +1865 other locations,"Job Security, Skill Development","Promotions, Salary"
6,Infosys,3.5,(49.9k),IT Services & Consulting,Bengaluru +247 other locations,Job Security,"Promotions, Salary, Work Satisfaction"
7,HCLTech,3.4,(47k),IT Services & Consulting,Chennai +232 other locations,"Promotions, Salary, Work Satisfaction",None
8,ICICI Bank,4.0,(46.7k),Banking,Mumbai +1449 other locations,"Job Security, Promotions, Skill Development",None
9,Tech Mahindra,3.3,(44.2k),IT Services & Consulting,Hyderabad +323 other locations,"Promotions, Salary, Work Satisfaction",None
10,Genpact,3.6,(43.4k),Analytics & KPO,Hyderabad +181 other locations,Job Security,"Promotions, Salary, Work Satisfaction"
11,TP,3.9,(39.7k),BPO,Mumbai +259 other locations,"Work Life Balance, Job Security, Skill Develop...",None
12,Axis Bank,3.6,(34.1k),Banking,Mumbai +1535 other locations,"Promotions, Work Satisfaction, Company Culture",None
13,Jio,4.4,(34.1k),Telecom,Mumbai +1966 other locations,"Job Security, Skill Development, Company Culture",None
14,Concentrix Corporation,3.5,(32.9k),BPO,Bengaluru +185 other locations,Job Security,"Promotions, Salary, Work Satisfaction"
15,Amazon,3.9,(32.4k),Internet,Bengaluru +521 other locations,"Company Culture, Work Life Balance, Salary",Promotions
16,Reliance Retail,3.9,(27.8k),Retail,Mumbai +1167 other locations,"Job Security, Skill Development, Work Life Bal...",Promotions
17,iEnergizer,4.6,(27.5k),BPO,Noida +55 other locations,"Company Culture, Work Life Balance, Work Satis...",None
18,LTM Limited,3.6,(27k),IT Services & Consulting,Bengaluru +146 other locations,"Promotions, Salary, Work Satisfaction",None
19,HDB Financial Services,3.9,(26.3k),NBFC,Mumbai +1099 other locations,"Promotions, Salary",None
20,IBM,3.9,(26.2k),IT Services & Consulting,Bengaluru +162 other locations,"Work Life Balance, Company Culture, Job Security",Promotions
21,Larsen & Toubro Limited,3.9,(24.4k),Engineering & Construction,Mumbai +781 other locations,"Job Security, Skill Development, Salary","Promotions, Work Life Balance"
22,Deloitte,3.6,(23.9k),Management Consulting,Hyderabad +186 other locations,"Promotions, Work Life Balance, Work Satisfaction",None
23,Kotak Mahindra Bank,3.6,(23k),Banking,Mumbai +697 other locations,"Promotions, Work Satisfaction, Company Culture",None
24,Reliance Industries,4.0,(20.6k),Oil & Gas,Jamnagar +822 other locations,"Job Security, Work Life Balance, Skill Develop...",Promotions
25,Vodafone Idea,3.9,(17.8k),Telecom,Pune +708 other locations,"Salary, Company Culture, Work Life Balance",Promotions
26,Bharti Airtel,3.8,(17.4k),Telecom,Gurugram +797 other locations,Promotions,None
27,BYJU'S,3.2,(16.4k),EdTech,Bengaluru +321 other locations,"Job Security, Company Culture, Work Life Balance",None
28,WNS,3.3,(15.6k),IT Services & Consulting,Pune +69 other locations,"Promotions, Salary, Work Satisfaction",None
29,IDFC FIRST Bank,4.0,(15.3k),Banking,Mumbai +746 other locations,"Salary, Work Life Balance, Skill Development",None
30,Ernst & Young,3.4,(15k),Management Consulting,Bengaluru +135 other locations,"Promotions, Work Life Balance, Work Satisfaction",None
31,IndusInd Bank,3.4,(14.6k),Banking,Mumbai +805 other locations,"Promotions, Company Culture, Work Satisfaction",None
32,AU Small Finance Bank,3.8,(14.5k),Banking,Jaipur +810 other locations,Salary,None
33,Tata Motors,4.1,(14.4k),Automobile,Pune +510 other locations,"Job Security, Company Culture, Work Life Balance",Promotions
34,Bajaj Finserv,3.9,(13.6k),NBFC,Pune +1220 other locations,"Salary, Skill Development, Job Security",None
35,Muthoot FinCorp,4.5,(13.3k),NBFC,Bengaluru +1126 other locations,"Company Culture, Work Life Balance, Job Security",None
36,Flipkart,3.9,(13.3k),Internet,Bengaluru +560 other locations,"Skill Development, Salary",Promotions
37,PwC,3.3,(13.1k),Management Consulting,Bengaluru +139 other locations,"Promotions, Work Life Balance, Work Satisfaction",None
38,HDFC Life,3.8,(12.4k),Insurance,Mumbai +724 other locations,Skill Development,Promotions
39,Mahindra & Mahindra,4.0,(12.3k),Automobile,Pune +570 other locations,"Job Security, Skill Development, Company Culture",Promotions
40,Infosys BPM,3.5,(12.3k),BPO,Bengaluru +95 other locations,Job Security,"Promotions, Salary, Work Satisfaction"
41,DXC Technology,3.6,(12.2k),IT Services & Consulting,Bengaluru +132 other locations,Work Life Balance,"Promotions, Salary, Work Satisfaction"
42,Bandhan Bank,3.7,(11.6k),Banking,Kolkata +1027 other locations,"Promotions, Work Satisfaction, Company Culture",None
43,Digitide Solutions,3.4,(10.6k),IT Services & Consulting,Hyderabad +276 other locations,"Promotions, Salary, Work Satisfaction",None
44,Yes Bank,3.7,(10.5k),Banking,Mumbai +545 other locations,"Job Security, Promotions, Company Culture",None
45,Mphasis,3.3,(10.5k),IT Services & Consulting,Bengaluru +64 other locations,"Promotions, Salary, Work Satisfaction",None
46,Tata Steel,4.0,(10.1k),Iron & Steel,Jamshedpur +228 other locations,"Work Life Balance, Job Security, Company Culture",Promotions
47,Quess,3.8,(10k),Recruitment,Bengaluru +768 other locations,"Promotions, Job Security",None
48,Asian Paints,3.9,(9.9k),Chemicals,Mumbai +565 other locations,"Salary, Skill Development, Job Security",Promotions
49,UltraTech Cement,4.1,(9.8k),Building Material,Mumbai +548 other locations,"Job Security, Skill Development, Company Culture",Promotions

In [70]:
Final.to_csv("ambitionbox_companies.csv", index=False)